version: "3.8"
services:  
  frontend:    
    build: ./frontend    
    ports:      
      - "3001:3001"    
    environment:      
      - NODE_ENV=production    
    depends_on:      
      - backend  
  backend:    
    build: ./backend    
    ports:      
      - "3000:3000"    
    environment:      
      - NODE_ENV=production